const Images = [
    {image: require('../assets/banners/alba-iulia.jpg')},
    {image: require('../assets/banners/arad.jpg')},
    {image: require('../assets/banners/brasov.jpg')},
    {image: require('../assets/banners/bucuresti.jpg')},
    {image: require('../assets/banners/cluj.jpg')},
    {image: require('../assets/banners/constanta.jpg')},
    {image: require('../assets/banners/craiova.jpg')},
    {image: require('../assets/banners/iasi.jpg')},
    {image: require('../assets/banners/oradea.jpg')},
    {image: require('../assets/banners/sibiu.jpg')},
    {image: require('../assets/banners/timisoara.jpg')},
  ];
  
  export const data = [
    {
      id: '1',
      title: 'Alba-Iulia',
      client1: 'Cretu Mark',
      client1description1:'Build your dream body with a little help. I will hellp you to gain muscle, and loose the unwanted weight.',
      client1description2:'Phone: 0770341884 \nE-mail: cretu.mark@gmail.com',
      client2: 'Pop Marius',
      client2description1:'Get that Body & Mind Power. These two go together, and I will show you how.',
      client2description2:'Phone: 0770345684 \nE-mail: pop.marius@gmail.com',
      image: Images[0].image,
    },
    {
      id: '2',
      title: 'Arad',
      client1:'Olariu Gabriel',
      client1description1: 'My purpose is to motivate people to live a happy and a healty life, by exercises and easy homecooked meals. ',
      client1description2:'Phone: 0770344335 \nE-mail: olariu.gabriel@yahoo.com',
      client2:'Calin Andrei',
      client2description1: 'Home / GYM center, wherever you are, I will help you to build your dream body.',
      client2description2:'Phone: 0770667335 \nE-mail: calin.andrei@yahoo.com',
      client3:'Pop Iulian',
      client3description1: 'Dream & Make it happen.',
      client3description2:'Phone: 0770337335 \nE-mail: pop.iulian@gmail.com',
      image: Images[1].image,
    },
    {
      id: '3',
      title: 'Brasov',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '4',
      title: 'Bucuresti',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '5',
      title: 'Cluj-Napoca',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '6',
      title: 'Constanta',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '7',
      title: 'Craiova',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '8',
      title: 'Iasi',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '9',
      title: 'Oradea',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '10',
      title: 'Sibiu',
      description: 'somethinf',
      image: Images[1].image,
    },
    {
      id: '11',
      title: 'Timisoara',
      description: 'somethinf',
      image: Images[1].image,
    },
];